drop table user if exists;
create table user (id bigint generated by default as identity, detail_id bigint,primary key (id));

drop table user_detail if exists;
create table user_detail (id bigint generated by default as identity,age int,primary key(id));